# Generated by Django 4.2.7 on 2023-12-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('en', models.CharField(max_length=1000)),
                ('bra', models.CharField(max_length=1000)),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
    ]
